import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const allPets = api.example.getAllPets.useQuery({ text: "Hello" });

  const user = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href='/pets'>
          Pets
        </Link>
        {!user.isSignedIn && <SignInButton />}
        {user.isSignedIn && <SignOutButton />}
      </main>
    </>
  );
};

export default Home;
